import { ReportData } from '../types/index.js';

export function generateHTML(data: ReportData): string {
  return `
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${data.title}</title>
  <style>
    body { 
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      color: #0f172a;
      line-height: 1.6;
      margin: 0;
      padding: 0;
    }
    .cover { 
      background: linear-gradient(135deg, #0a1931 0%, #1e3a8a 100%);
      color: #fff; 
      padding: 80px 40px; 
      text-align: center;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      justify-content: center;
    }
    .title { 
      font-size: 48px; 
      font-weight: 800; 
      margin-bottom: 20px;
      text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
    }
    .subtitle { 
      font-size: 24px; 
      margin-bottom: 40px;
      opacity: 0.9;
    }
    .meta {
      font-size: 18px;
      margin: 10px 0;
      opacity: 0.8;
    }
    .section { 
      margin: 60px 40px; 
      padding: 30px;
      background: #f8fafc;
      border-radius: 12px;
      box-shadow: 0 4px 6px rgba(0,0,0,0.05);
    }
    .page { page-break-after: always; }
    .page:last-child { page-break-after: auto; }
    .data-table {
      width: 100%;
      border-collapse: collapse;
      margin: 20px 0;
      background: white;
      border-radius: 8px;
      overflow: hidden;
    }
    .data-table th {
      background: #3b82f6;
      color: white;
      padding: 15px;
      text-align: left;
      font-weight: 600;
    }
    .data-table td {
      padding: 12px 15px;
      border-bottom: 1px solid #e2e8f0;
    }
    .data-table tr:nth-child(even) {
      background: #f8fafc;
    }
    .metric-card {
      background: white;
      border: 1px solid #e2e8f0;
      border-radius: 8px;
      padding: 20px;
      margin: 15px 0;
      display: inline-block;
      min-width: 200px;
    }
    .metric-value {
      font-size: 32px;
      font-weight: 700;
      color: #059669;
    }
    .metric-label {
      color: #64748b;
      font-size: 14px;
    }
    .footer { 
      color: #64748b; 
      font-size: 12px; 
      text-align: center; 
      margin-top: 60px;
      padding: 20px;
      border-top: 1px solid #e2e8f0;
    }
    .chart-placeholder {
      background: #f1f5f9;
      border: 2px dashed #cbd5e1;
      border-radius: 8px;
      padding: 40px;
      text-align: center;
      margin: 20px 0;
      color: #64748b;
    }
  </style>
</head>
<body>
  <div class="cover page">
    <div class="title">${data.title}</div>
    <div class="subtitle">${data.subtitle || 'Professional Report'}</div>
    <div class="meta">Generated on: ${new Date(
      data.date
    ).toLocaleDateString()}</div>
    <div class="meta">Author: ${data.author || 'System'}</div>
    <div class="meta">Report Type: A - Premium Analysis</div>
  </div>

  <div class="section page">
    <h1>Executive Summary</h1>
    <div class="metric-card">
      <div class="metric-value">${
        (data.data as any)?.summary?.totalItems || 50
      }</div>
      <div class="metric-label">Total Items Analyzed</div>
    </div>
    <div class="metric-card">
      <div class="metric-value">${Math.round(
        (data.data as any)?.summary?.averageScore || 65
      )}</div>
      <div class="metric-label">Average Score</div>
    </div>
    <div class="metric-card">
      <div class="metric-value">${
        (data.data as any)?.summary?.topPerformers?.length || 5
      }</div>
      <div class="metric-label">Top Performers</div>
    </div>
  </div>

  <div class="section page">
    <h1>Detailed Analysis</h1>
    <table class="data-table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Score</th>
          <th>Performance</th>
        </tr>
      </thead>
      <tbody>
        ${((data.data as any)?.data || [])
          .slice(0, 20)
          .map(
            (item: any) => `
          <tr>
            <td>${item.label}</td>
            <td>${item.score}</td>
            <td>${
              item.score > 70
                ? 'Excellent'
                : item.score > 50
                ? 'Good'
                : 'Needs Improvement'
            }</td>
          </tr>
        `
          )
          .join('')}
      </tbody>
    </table>
  </div>

  <div class="section page">
    <h1>Charts & Visualizations</h1>
    <div class="chart-placeholder">
      {{CHART_1}}
    </div>
    <div class="chart-placeholder">
      {{CHART_2}}
    </div>
  </div>

  <div class="footer">
    <p>This is an automated report generated by BrandLight Advanced PDF Service</p>
    <p>© ${new Date().getFullYear()} BrandLight. All rights reserved.</p>
  </div>
</body>
</html>
  `;
}
